### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AmazingMech2418** [Repl-it-Coders/fs#1]
Is this supposed to create file system images and manipulate them? Also, what filesystem format are we using? I'm guessing either exFAT, NTFS, or ext4 since those are most common...

**Comment by programmeruser2** [comment]
I'm pretty sure that this repo has @firefish111's custom filesystem. Where's the source code though?

**Comment by AmazingMech2418** [comment]
That's what I don't know...

**Comment by whippingdot** [comment]
Hello, what is this @firefish111. Can you please not create random repos like this. Create a README and describe what it is first. Transfer this repo to your account. This repo is not at all related to our org. You can transfer it to your account.

**Comment by zghwi** [comment]
yeah @programmeruser2  i only see a `fn main() {}` lmao it is an empty main function how can we create a filesystem with an EMPTY FUNCTION smh smh
we can do it in go it is better, i'll fork and push a new directory to make one with go cuz it is awesome

**Comment by programmeruser2** [comment]
In firefish's [initial commit](https://github.com/Repl-it-Coders/fs/commit/e945a0468db8acdf64886c3bf6fdf645db7be58d), there was a C file with some source code, but I don't know what it's supposed to do....

**Comment by zghwi** [comment]
oh yeah
maybe the build file idk
###### wait what am i dumb you cant build rust files to c lol

**Comment by AmazingMech2418** [comment]
> oh yeah
> maybe the build file idk
> 
> ###### wait what am i dumb you cant build rust files to c lol

Well, maybe it was written in C and we have to convert to Rust?

**Comment by whippingdot** [comment]
Why you bully me, I guess you all are working on this together. What is it btw

**Comment by zghwi** [comment]
it is a filesystem written in Rust
but im trying to make it in Go

**Comment by zghwi** [comment]
firefish is not talking anymore

**Comment by iop3** [comment]
stale?

**Comment by firefish111** [comment]
wait i never knew this issue existed

**Comment by iop3** [comment]
haha lol
